# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image to build the server
FROM node:20-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the source code
COPY src ./src
COPY tsconfig.json ./

# Build the project
RUN npm run build

# Use a smaller Node.js image for the final output
FROM node:20-alpine AS release

# Set working directory
WORKDIR /app

# Copy built files and package.json
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./

# Install only production dependencies
RUN npm ci --omit=dev

# Set environment variables required by the server
ENV LLAMA_CLOUD_INDEX_NAME="<YOUR_INDEX_NAME>"
ENV LLAMA_CLOUD_PROJECT_NAME="<YOUR_PROJECT_NAME>"
ENV LLAMA_CLOUD_API_KEY="<YOUR_API_KEY>"

# Set the entry point to run the server
ENTRYPOINT ["node", "build/index.js"]
